apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-app-dep
spec:
  selector:
    matchLabels:
      app: the-project-app
  template:
    metadata:
      labels:
        app: the-project-app

    spec:
      containers:
        - name: the-project-app
          image: lucasnicolas/the-project-app
