apiVersion: v1
kind: Service
metadata:
  name: the-project-service
spec:
  type: NodePort
  selector:
    app: the-project-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 1234
      targetPort: 9007